name: rapids tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.MAVEN_REPO_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.MAVEN_REPO_AWS_ACCESS_KEY_SECRET}}
        aws-region: us-east-1

    - uses: actions/checkout@v2

    ## Useful for debugging problems - CI will pause and provide an ssh connection
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
